// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npeydyimkdmlegzrzhgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wZXlkeWlta2RtbGVnenJ6aGdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MDg1ODgsImV4cCI6MjA2NzE4NDU4OH0.0FGJ1YBeZ1mUNhjeefEkARhal2QOCOD6EBsoFR5Cnlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});